name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: SurviKit.jar
          path: build/libs/*.jar
