name: 给不会构建的笨蛋用的 workflow (不是)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read        # 默认
  actions: write        # 用于上传 artifacts

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SurviKit
          path: build/libs/*.jar

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: SurviKit

      - name: Inspect artifact
        run: ls -R .